<? $IMG = $this->layout()->settings['img']; ?>

<div class="page-header">
  <h1>Модификации товара <?=$item->name;?></h1>
</div>

<a href="<?=$this->url('admin/default', array('controller'=>'variants', 'action'=>'add', 'id'=> $itemId));?>" class="btn btn-primary btn-lg mrg-b-lg">
  Добавить модификацию
</a>

<? $variants = $item->getVariants(['parentGroupLoad',]); ?>
<? if ($variants->count()) : ?>
<table class="table table-striped table-sortable">
    <thead>
        <tr>
            <th></th>
            <th>ID</th>
            <th>Имя</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
    <? foreach ($variants as $variant) : ?>
        <? $variantParentGroup = $variant->getParentGroup(); ?>
        <tr id="<?=$variant->id;?>" class="table-row-variant-id-<?=$variant->id;?>">
            <td><input type="checkbox" name="ids[]" value="<?=$variant->id;?>" class="js-variant-checkbox"/></td>
            <td><?=$variant->id;?></td>

            <td>
                <a href="<?=$this->url('admin/default', ['controller'=>'variants', 'action'=>'edit', 'id'=> $variant->id]);?>">
                    <?=$variant->name;?>
                </a><br/>
                <?=$variant->getName();?>
            </td>
            <td>
                <a href="<?=$this->url('admin/default', array('controller'=>'variants', 'action'=>'edit', 'id'=>$variant->id));?>" class="btn btn-default btn-xs" role="button" title="Редактировать">
                  <span class="glyphicon glyphicon-edit" aria-hidden="true"></span> 
                </a>
                <a href="<?=$this->url(
                        'home/catalog/group/variant', 
                        [   'groupId'=>$variantParentGroup->id, 
                            'groupName'=>$this->translit($variantParentGroup->name),
                            'variantId'=>$variant->id, 
                            'variantName'=>$this->translit($variant->name),
                            ]);?>" target="_blank" class="btn btn-default btn-xs" role="button" title="На сайте">
                  <span class="glyphicon glyphicon-eye-open" aria-hidden="true"></span> 
                </a>
                <button title="Удалить" role="button" class="js-ajax-remove btn btn-default btn-xs" 
                        postparamname="variantid" 
                        variantid="<?=$variant->id;?>" 
                        url="<?=$this->url('admin/default', ['controller'=>'variants', 'action'=>'remove']);?>" 
                        confirm='Удалить модификацию "<?=$variant->name;?>"?' 
                        removeselector=".table-row-variant-id-<?=$variant->id;?>">
                    <span aria-hidden="true" class="glyphicon glyphicon-remove"></span>
                </button>
            </td>
        </tr>
    <? endforeach; ?>
    </tbody>
</table>

<? endif; ?>

<button title="Удалить отмеченные" class="js-ajax-bulk-remove btn btn-default btn-md" role="button"
        checkboxselector=".js-variant-checkbox" 
        postparamname="variantid" 
        url="<?=$this->url('admin/default', ['controller'=>'variants', 'action'=>'remove']);?>" 
        confirm='Удалить отмеченные модификации?' 
        removeselector=".table-row-variant-id-">
  <span class="glyphicon glyphicon-remove" aria-hidden="true"></span> 
</button>