<?$this->layout()->title = 'Вход в личный кабинет';?>

<div id="cmsms_row_56db2fe61faed" class="cmsms_row cmsms_color_scheme_default">
    <div class="cmsms_row_outer_parent">
        <div class="cmsms_row_outer">
            <div class="cmsms_row_inner">
                <div class="cmsms_row_margin cmsms_11">
                    <div class="cmsms_column one_half">
                        <?php echo $this->partial('partial/form/login.phtml', array( 'form' => $form, )); ?>
                    </div>
                    <div class="cmsms_column one_half">
                        <div>
                            <a href="<?=$this->url('auth/default', ['controller'=>'user', 'action'=>'registration']);?>">Регистрация</a>
                        </div>
                        <div>
                            <a href="<?=$this->url('auth/default', ['controller'=>'user', 'action'=>'resetpassword']);?>">Восстановить пароль</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>



