

<div class="tabs-block">
    <?php echo $this->navigation('Navigation')->menu()
            ->setContainer($this->navigation('Navigation')->findOneBy('id','home-lk'))
            ->setMaxDepth(0)
            ->setPartial(array('partial/lkMenu.phtml', 'Account'))
            ;
    ?>
</div>

<?$this->layout()->title = 'Личный кабинет';?>
<div id="cmsms_row_56db2fe61faed" class="cmsms_row cmsms_color_scheme_default">
    <div class="cmsms_row_outer_parent">
        <div class="cmsms_row_outer">
            <div class="cmsms_row_inner">
                <div class="cmsms_row_margin cmsms_11">
                    <div class="cmsms_column one_sixth">
                        меню ЛК
                    </div>
                    <div class="cmsms_column one_fifth">
                        контент ЛК
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
