<?php echo $this->doctype(); ?>

<html lang="ru">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle() ?>
        
        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>
        <?php echo $this->headLink()
            //->appendStylesheet(array('rel' => 'stylesheet', 'href' => 'http://zf.3259404.local/css/reset.min.css'))
            //->appendStylesheet($this->basePath('/css/dashboard.css'))
            ->appendStylesheet(array('rel' => 'stylesheet', 'href' => 'http://zf.3259404.local/css/normalize.css'))
            ->appendStylesheet(array('rel' => 'stylesheet', 'href' => 'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css'))
            ->appendStylesheet(array('rel' => 'stylesheet', 'href' => 'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap-theme.min.css'))
            ->appendStylesheet(array('rel' => 'stylesheet', 'href' => 'http://getbootstrap.com/examples/dashboard/dashboard.css'))
            ->appendStylesheet(array('rel' => 'stylesheet', 'href' => 'https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.15.35/css/bootstrap-datetimepicker.min.css'))
            ->appendStylesheet(array('rel' => 'stylesheet/less', 'href' => $this->basePath('/css/admin.less')))
        ?>
        <!-- JS scripts -->
        <?php echo $this->headScript() //@TODO перенести вниз
            /*->appendFile('https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js', 'text/javascript')
            ->appendFile('https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js', 'text/javascript')
            //->appendFile('https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.10.6/moment.min.js', 'text/javascript')
            ->appendFile('https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.10.6/moment-with-locales.min.js', 'text/javascript')
            ->appendFile('https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.10.6/locale/ru.js', 'text/javascript')
            ->appendFile('https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.15.35/js/bootstrap-datetimepicker.min.js', 'text/javascript')
            ->appendFile('http://zf.3259404.local/js/client.js','text/javascript')*/
        ?>
    </head>
    <body>
        <nav class="navbar navbar-inverse navbar-fixed-top">
            <div class="container-fluid">
                <div class="navbar-header">
                    <button aria-controls="navbar" aria-expanded="false" data-target="#navbar" data-toggle="collapse" class="navbar-toggle collapsed" type="button">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a href="<?=$this->url('admin');?>" class="navbar-brand">Панель Администрирования</a>
                </div>
                <div class="navbar-collapse collapse" id="navbar">
                    <ul class="nav navbar-nav navbar-right">
                        <li><a href=""><?=$this->layout()->admin->name;?></a></li>
                        <li><a href=""><?=$this->layout()->admin->email;?></a></li>
                        <li><a href="<?=$this->url('auth/admin/logout', array());?>">Выход</a></li>
                    </ul>
                </div>
            </div>
        </nav>
        <div class="container-fluid">
            <div class="row">
                <div class="col-sm-3 col-md-2 sidebar">
                    <?php // <-- Add this !!
                    //echo $this->navigation('Navigation')->menu()->setPartial(array('partial/sideMenu.phtml', 'Admin'));
                    ?>
                    <?php echo $this->navigation('Navigation')->menu()->setContainer($this->navigation('Navigation')->findOneBy('id','admin'))->setMaxDepth(1)->setPartial(array('partial/sideMenu.phtml', 'Admin'));?>
                </div>
                <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
                    <? if ($this->flashMessenger()->hasMessages()) { ?>
                    <div class="flash-message-block">
                        <? echo $this->flashMessenger()->render(\Zend\Mvc\Controller\Plugin\FlashMessenger::NAMESPACE_SUCCESS, ['alert', 'alert-success', 'alert-dismissible']); ?>
                    </div>
                    <? } ?>
                    <?php echo $this->navigation('Navigation')->breadcrumbs()->setContainer($this->navigation('Navigation')->findOneBy('id','admin'))->setMinDepth(0); ?>
                    <?php echo $this->content; ?>
                </div>
            </div>
        </div>
        
        
        
        <?php echo $this->inlineScript()
            ->appendFile('https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js', 'text/javascript')
            ->appendFile('http://cdnjs.cloudflare.com/ajax/libs/less.js/2.3.1/less.min.js', 'text/javascript')
            ->appendFile('https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js', 'text/javascript')
            ->appendFile('https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.10.6/moment.min.js', 'text/javascript')
            ->appendFile('https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.10.6/moment-with-locales.min.js', 'text/javascript')
            ->appendFile('https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.10.6/locale/ru.js', 'text/javascript')
            ->appendFile('https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.15.35/js/bootstrap-datetimepicker.min.js', 'text/javascript')
                
            //->appendFile('http://zf.3259404.local/js/html.sortable.min.js','text/javascript')    
            ->appendFile('https://code.jquery.com/ui/1.11.4/jquery-ui.js', 'text/javascript')

            ->appendFile('http://zf.3259404.local/js/common.js','text/javascript')
            ->appendFile('http://zf.3259404.local/js/admin.js','text/javascript')
            //->appendFile('http://zf.3259404.local/js/client.js','text/javascript')
        ?>
    </body>
</html>
