<div class="page-header">
  <h1>Управление администраторами <small>Все администраторы</small></h1>
</div>

<?php
$form->prepare();
$formLabel = $this->plugin('formLabel');

// Render the opening tag
echo $this->form()->openTag($form);
?>
<div class="row">
    <div class='col-xs-2'>
        <?php
            $email = $form->get('email');
            echo $this->formInput($email);
            echo $this->formElementErrors($email);
        ?>
    </div>
</div>
<div class="row js-datetimepicker-start-end">
    <div class='col-xs-2'>
        <div class="input-group date datetimepicker-start" >
            <?php $elem = $form->get('date_register_start'); echo $this->formInput($elem); ?>
            <span class="input-group-addon">
                <span class="glyphicon glyphicon-calendar"></span>
            </span>
        </div>
        <? echo $this->formElementErrors($elem);?>
    </div>
    <div class='col-xs-2'>
        <div class='input-group date datetimepicker-end'>
            <?php $elem = $form->get('date_register_end'); echo $this->formInput($elem); ?>
            <span class="input-group-addon">
                <span class="glyphicon glyphicon-calendar"></span>
            </span>
        </div>
        <? echo $this->formElementErrors($elem);?>
    </div>
</div>    
<div class="row js-datetimepicker-start-end">
    <div class='col-xs-2'>
        <div class="input-group date datetimepicker-start" >
            <?php $elem = $form->get('date_last_login_start'); echo $this->formInput($elem); ?>
            <span class="input-group-addon">
                <span class="glyphicon glyphicon-calendar"></span>
            </span>
        </div>
        <? echo $this->formElementErrors($elem);?>
    </div>
    <div class='col-xs-2'>
        <div class='input-group date datetimepicker-end'>
            <?php $elem = $form->get('date_last_login_end'); echo $this->formInput($elem); ?>
            <span class="input-group-addon">
                <span class="glyphicon glyphicon-calendar"></span>
            </span>
        </div>
        <? echo $this->formElementErrors($elem);?>
    </div>
</div>    


<?php echo $this->formElement($form->get('search')) ?>

<?php echo $this->form()->closeTag() ?>

<table class="table table-striped">
    <thead>
        <tr>
            <th>id</th>
            <th>Email</th>
            <th>Роль</th>
            <th>Регистрация</th>
            <th>Последний вход</th>
            <th>Действия</th>
        </tr>
    </thead>
    <tbody>
        <?  foreach ($users as $user) { ?>
        <tr>
            <td><?=$user->id;?></td>
            <td><?=$user->email;?></td>
            <td><?=$user->role;?></td>
            <td><?=$this->dateFormat($user->date_register, IntlDateFormatter::MEDIUM, IntlDateFormatter::MEDIUM, "ru_RU");?></td>
            <td><?=$this->dateFormat($user->date_last_login, IntlDateFormatter::MEDIUM, IntlDateFormatter::MEDIUM, "ru_RU");?></td>
            <td>
                <a href="<?=$this->url('admin/default', array('controller'=>'sysusers', 'action'=>'edit', 'id'=>$user->id));?>" class="btn btn-default btn-xs" role="button" title="Редактировать права">
                  <span class="glyphicon glyphicon-edit" aria-hidden="true"></span> 
                </a>
            </td>
        </tr>
        <? } ?>
    </tbody>
</table>

<?php if ($users instanceof Zend\Paginator\Paginator)  
        echo $this->paginationControl($users, 'sliding', array('partial/paginatorAdmin.phtml', 'admin'),
            array(
                'route' => 'admin/default', 
                'params' => ['controller' => 'users', 'action' => 'index'],
                'options' => ['query' => $query],
            ));
    ?>