<? if (count($cart->getItems('tyres'))) { ?>
<section class="content_wrap fullwidth cmsms_woo">
    <!--_________________________ Start Content _________________________ -->
    <div role="main" class="middle_content entry">
        <style type="text/css"></style>
        <div class="woocommerce">
            <!--div class="woocommerce-message">message</div-->

            <div style="margin-bottom: 20px;">
                Корзина действительна до <?=date("d-m-Y h:i:s", $cart->date_created+24*60*60);?>
            </div>
            
            <form method="post" action="<?=$this->url('home/cart/default', ['controller' => 'index', 'action' => 'updateitemcount']);?>">
                <table cellspacing="0" class="shop_table shop_table_responsive cart">
                    <thead>
                        <tr>
                            <th class="product-remove">&nbsp;</th>
                            <th class="product-thumbnail">&nbsp;</th>
                            <th class="product-name">Наименование</th>
                            <th class="product-price">Цена</th>
                            <th class="product-quantity">Кол-во</th>
                            <th class="product-subtotal">Сумма</th>
                        </tr>
                    </thead>
                    <tbody>
                        <? foreach ($cart->getItems('tyres') as $item) { ?>
                        <tr class="cart_item">
                            <td class="product-remove">
                                <a  title="Удалить" class="remove" href="<?=$this->url('home/cart/default', ['controller' => 'index', 'action' => 'removefromcart', 'id' => $item->id]);?>">×</a>					
                            </td>
                            <td class="product-thumbnail">
                                <a href="<?=$item->url;?>">
                                    <img width="90" height="90" class="attachment-shop_thumbnail size-shop_thumbnail wp-post-image" src="<?=$item->image;?>">
                                </a>
                            </td>
                            <td data-title="Product" class="product-name">
                                <a href="<?=$item->url;?>"><?=$item->name;?></a>					
                            </td>
                            <? if ($item->isRelevant()) { ?>
                            <td data-title="Price" class="product-price">
                                <span class="amount"><?=$item->price;?></span>					
                            </td>
                            <td data-title="Quantity" class="product-quantity">
                                <div class="quantity">
                                    <input type="number" size="4" class="input-text qty text" title="Количество" value="<?=$item->count;?>" name="count[<?=$item->id;?>]" max="" min="1" step="1">
                                </div>
                            </td>
                            <td data-title="Total" class="product-subtotal">
                                <span class="amount"><?=$item->getSumm();?></span>					
                            </td>
                            <? } else { ?>
                            <td colspan="3">
                                Цена на товар могла измениться, обновите выбраную позицию,<br/>для этого перейдите к товару <a href="<?=$item->url;?>">по ссылке</a>
                            </td>
                            <? } ?>
                        </tr>
                        <? } ?>
                        <tr>
                            <td class="actions" colspan="6">
                                <input type="submit" value="Пересчитать корзину" name="update_cart" class="button">
                            </td>
                        </tr>
                    </tbody>
                </table>
            </form>

            <div class="cart-collaterals">
                <div class="cart_totals ">
                    <table cellspacing="0" class="shop_table shop_table_responsive">
                        <tbody>
                            <tr class="order-total">
                                <th>Итого</th>
                                <td data-title="Total"><strong><span class="amount"><?=$cart->getTotalSumm();?></span></strong> </td>
                            </tr>
                        </tbody>
                    </table>
                    <div class="wc-proceed-to-checkout">
                        <a class="checkout-button button alt wc-forward" href="<?=$this->url('home/cart/default', ['controller' => 'index', 'action' => 'order']);?>">
                            Оформить заказ
                        </a>
                    </div>
                </div>
            </div>
        </div>
        <div class="cl"></div>
    </div>
<!-- _________________________ Finish Content _________________________ -->

</section>

<? } else { ?>
Пока в Вашей корзине пусто
<? } ?>
