<?$this->layout()->title = 'Заказ отправлен.';?>


<div id="cmsms_row_56db2fe61faed" class="cmsms_row cmsms_color_scheme_default">
    <div class="cmsms_row_outer_parent">
        <div class="cmsms_row_outer">
            <div class="cmsms_row_inner">
                <div class="cmsms_row_margin cmsms_11">
                    <div class="cmsms_column one_half">
                        
                        Ваша заказ отправлен, спасибо. Наш менеджер обязательно с вами свяжется.
                        
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

