<? if (count($cart->getItems('tyres'))) { ?>


    <ul class="cart_list product_list_widget ">
        <? foreach ($cart->getItems('tyres') as $item) { ?>
        <li class="mini_cart_item">
            <a data-product_sku="" data-product_id="1960" title="Remove this item" class="remove" href="<?=$this->url('home/cart/default', ['controller' => 'index', 'action' => 'removefromcart', 'id' => $item->id]);?>">×</a>													
            <a href="<?=$item->url;?>">
                <img width="90" height="90" class="attachment-shop_thumbnail size-shop_thumbnail wp-post-image" src="<?=$item->image;?>">
                <?=$item->name;?>&nbsp;							
            </a>
            <span class="quantity"><?=$item->count;?> × <span class="amount"><?=$item->price;?> RUB</span></span>					
        </li>
    <? } ?>
    </ul><!-- end product list -->


    <p class="total"><strong>Итого:</strong> <span class="amount"><?=$cart->getTotalSumm();?> RUB</span></p>


    <p class="buttons">
        <a class="button wc-forward" style="font-size:12px;" href="<?=$this->url('home/cart')?>">Корзина</a>
        <a class="button checkout wc-forward" style="font-size:12px;" href="<?=$this->url('home/cart/default', ['controller' => 'index', 'action' => 'order']);?>">Оформить</a>
    </p>

<? } else { ?>
Пока в Вашей корзине пусто
<? } ?>
