<? if (count($cart->getItems())) { ?>
<table>
    <thead>
        <tr>
            <th colspan="3">Товары в вашей корзине</th><th>Кол-во</th><th>Сумма</th>
        </tr>
    </thead>    
    <tbody>
        <?php foreach ($cart->getItems() as $item) { 
            $variant = $item->getVariant(); 
            $href = $this->url('home/catalog/group/variant', [
                'groupId' => $variant->getParentGroup()->id, 
                'groupName' => $this->translit($variant->getParentGroup()->name),
                'variantId' => $variant->id, 
                'variantName' => $this->translit($variant->name)
                ]);
            ?> 
        <tr id="cart-item-variant-id-<?=$item->variant_id;?>">
            <td>
                <a href="<?=$href;?>">
                    <img src="<?=$this->layout()->settings['img']['HOST'].$this->layout()->settings['img']['VARIANTS_SMALLIMAGES']?>/<?=$item->getVariant()->getProp('image');?>" width="60px"/>
                </a>
            </td>
            <td colspan="2">
                <a href="<?=$href;?>">
                    <?=$item->getVariant()->name;?>
                </a>
            </td>
            <td><?=$item->count;?></td>
            <td><?=$this->numberFormat($item->getSumm(), \NumberFormatter::DECIMAL);?></td>
        </tr>
        <? } ?>
    </tbody>
    <tfoot>
        <tr>
            <td colspan="2">Всего товаров в корзине: <?=$cart->getTotalCount();?></td>
            <td colspan="2" align="right">Сумма заказа:</td>
            <td><?=$cart->getTotalSumm();?></td>
        </tr>
    </tfoot>
</table>

<? } else { ?>
Пока в Вашей корзине пусто
<? } ?>
