<? $this->layout()->title = 'Модели шин '.$brand->name; ?>
<? $IMG = $this->layout()->settings['images']; ?>

<section class="content_wrap fullwidth cmsms_woo">

<!--_________________________ Start Content _________________________ -->
<div role="main" class="middle_content entry">
	<ul class="products cmsms_products">
        <? foreach ($tyreModels as $tyreModel) { 
            $url = $this->url('home/tyres/tyre', ['brandName' => $brand->name, 'modelName' => $tyreModel->name]);?>
        <li class="post-1919 product type-product status-publish has-post-thumbnail product_cat-brake-parts sale shipping-taxable purchasable product-type-simple product-cat-brake-parts instock">
            <div class="product_outer">
                <? if ($tyreModel->isSale()) { ?>
                <span class="onsale">Sale!</span>
                <? } ?>
                <article class="product_inner">
                    <? $images = $tyreModel->getImages(); $firstImage = array_shift($images); ?>
                    <figure class="cmsms_product_img preloader">
                        <a href="<?= $url ?>">
                            <img width="250" height="250" sizes="(max-width: 250px) 100vw, 250px" 
                                class="attachment-shop_catalog size-shop_catalog wp-post-image" 
                                src="<?=($firstImage != null) ? implode('', [$IMG['host'],$IMG['tyres'],$IMG['models'],$firstImage]) : 'holder.js/300x300/#fff:#aaa/text:Нет фото';?>">				
                        </a>
                    </figure>
                    <div class="cmsms_product_cont">
                        <footer class="cmsms_product_footer entry-meta">
                            <div class="cmsms_product_footer_inner">
                            <a href="<?= $url ?>" class="cmsms_details_button cmsms_theme_icon_details">
                                <span style="width: 130px;">Выбрать размер</span>
                            </a>					
                            </div>
                        </footer>
                        <div class="cmsms_product_info">
                            
                        </div>
                        <div class="cl"></div>
                        <header class="cmsms_product_header entry-header">
                            <h6 class="cmsms_product_title entry-title">
                                <a href="<?= $url ?>">
                                    <?= $tyreModel->name; ?>
                                </a>
                            </h6>
                        </header>

                        <span class="price">
                            <ins><span class="amount">от <?=$tyreModel->getMinPrice();?> RUB</span></ins>
                        </span>
                        			
                    </div>
                </article>
			</div>
        </li>
        <? } ?>
    </ul>
</div>
<!-- _________________________ Finish Content _________________________ -->
</section>
