<? $this->layout()->title = 'Модели шин '.$brand->name; ?>
<? $IMG = $this->layout()->settings['images']; ?>
<div class="cmsms_row cmsms_color_scheme_default" id="cmsms_row_56c81bb8b9a85">
    <div class="cmsms_row_outer_parent">
        <div class="cmsms_row_outer">
            <div class="cmsms_row_inner">
                <? foreach ($tyreModels as $tyreModel) { ?>
                    <div style="width: 10%; float:left;">
                        <a href="<?= $this->url('home/tyres/tyre', ['brandName' => $brand->name, 'modelName' => $tyreModel->name]); ?>">
                            <? $images = $tyreModel->getImages(); $firstImage = array_shift($images); ?>
                        <? if ($firstImage != null) { ?>
                            <img width="120" height="120" 
                                 src="<?=implode('', [$IMG['host'],$IMG['tyres'],$IMG['models'],$firstImage])?>" 
                                 class="attachment-shop_single size-shop_single wp-post-image" 
                                 alt="<?=$firstImage;?>" title="" 
                                 sizes="(max-width: 500px) 100vw, 500px" />
                        <? } else { ?>
                            нет фото
                        <? } ?>
                        <?= $tyreModel->name; ?>
                        </a>
                    </div>
                <? } ?>
                <div style="clear: both;"></div>
            </div>
        </div>
    </div>
</div>