<?/*<div class="tabs-block">
    <div class="tabs">
        <a class="tab active" href="<?= $this->url('account/default', array('controller' => 'index')); ?>">Настройки</a>
        <a class="tab" href="<?= $this->url('account/default', array('controller' => 'orders')); ?>">Мои заказы</a>
        <a class="tab" href="<?= $this->url('account/default', array('controller' => 'finances')); ?>">Финансы</a>
        <a class="tab" href="<?= $this->url('account/default', array('controller' => 'contacts')); ?>">Контакты</a>
    </div>
    <div class="contents">
        <div class="content active">
            asdasd
        </div>
    </div>
</div>*/?>