<div class="page-header">
  <h1>Новые модификации</h1>
</div>

<?php
$form->prepare();
$formLabel = $this->plugin('formLabel');
// Render the opening tag
echo $this->form()->openTag($form);
?>
<div class="row">
    <div class='col-xs-2'>
        <?php $name = $form->get('name');
        echo $this->formInput($name);
        echo $this->formElementErrors($name); ?>
    </div>
    <div class='col-xs-2'>
        <?php
            $code_1c = $form->get('code_1c');
            echo $this->formInput($code_1c);
            echo $this->formElementErrors($code_1c);
        ?>
    </div>
    <div class='col-xs-2'>
        <?php $elem = $form->get('article');
            echo $this->formInput($elem);
            echo $this->formElementErrors($elem); ?>
    </div>
    <div class='col-xs-2'>
        <?php
            $elem = $form->get('status');
            echo $this->formSelect($elem);
            echo $this->formElementErrors($elem);
        ?>
    </div>
    <div class='col-xs-2'>
        <?php
            $elem = $form->get('price_min');
            echo $this->formInput($elem);
            echo $this->formElementErrors($elem);
        ?>
    </div>
    <div class='col-xs-2'>
        <?php
            $elem = $form->get('price_max');
            echo $this->formInput($elem);
            echo $this->formElementErrors($elem);
        ?>
    </div>
</div>
<?php echo $this->formElement($form->get('search')) ?>

<?php echo $this->form()->closeTag() ?>


<table class="table table-striped">
    <thead>
        <tr>
            <th></th>
            <th>id</th>
            <th>Наименование</th>
            <th>Код 1С</th>
            <th>Артикул</th>
            <th>Статус</th>
            <th>Цена</th>
        </tr>
    </thead>
    <tbody>
        <?  foreach ($newVariants as $newVariant) { ?>
        <tr>
            <td><input type="checkbox" name="ids[]" value="<?=$newVariant->id;?>"/></td>
            <td><?=$newVariant->id;?></td>
            <td><?=$newVariant->name;?></td>
            <td><?=$newVariant->code_1c;?></td>
            <td><?=$newVariant->article;?></td>
            <td><?=$newVariant->status.' - '.$statuses[$newVariant->status]->name;?></td>
            <td><?=$newVariant->price;?></td>
            <td>
                <a href="#" class="btn btn-default btn-xs" role="button" title="Добавить к товару">
                  <span class="glyphicon glyphicon-log-in" aria-hidden="true"></span> 
                </a>
                <button data-toggle="modal" data-target="#create-new-variant-modal-<?=$newVariant->id;?>" class="btn btn-default btn-xs" role="button" title="Создать товар">
                  <span class="glyphicon glyphicon-open-file" aria-hidden="true"></span> 
                </button>
            </td>
        </tr>
        <? } ?>
    </tbody>
</table>
<a href="#" class="btn btn-default btn-md" role="button" title="Добавить к товару">
  <span class="glyphicon glyphicon-log-in" aria-hidden="true"></span> 
</a>
<a href="#" class="btn btn-default btn-md" role="button" title="Создать товар">
  <span class="glyphicon glyphicon-open-file" aria-hidden="true"></span> 
</a>

<!-- 
Модальные окна для создания товара
-->
<?  foreach ($newVariants as $newVariant) { ?>
<div class="modal fade" id="create-new-variant-modal-<?=$newVariant->id;?>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel"><?=$newVariant->name;?></h4>
      </div>
      <div class="modal-body">
        ...
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div>
  </div>
</div>
<? } ?>


<?php if ($newVariants instanceof Zend\Paginator\Paginator)  
        echo $this->paginationControl($newVariants, 'sliding', array('partial/paginatorAdmin.phtml', 'admin'),
            array(
                'route' => 'admin/default', 
                'params' => ['controller' => 'catalog', 'action' => 'newvariants'],
                'options' => ['query' => $query],
            ));
    ?>