<div class="page-header">
  <h1>Поставщики шин</h1>
</div>

<? if ($providers->count()) : ?>
<table class="table table-striped table-sortable">
    <thead>
        <tr>
            <th></th>
            <th>ID</th>
            <th>Имя</th>
            <th>Файлы</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
    <? foreach ($providers as $provider) : ?>
        <tr id="<?=$provider->id;?>" class="table-row-provider-id-<?=$provider->id;?>">
            <td><input type="checkbox" name="ids[]" value="<?=$provider->id;?>" class="js-provider-checkbox"/></td>
            <td><?=$provider->id;?></td>
            <td><?=$provider->name; ?></td>
            <td><?=$provider->files;?></td>
            <td>
                <a href="<?=$this->url('admin/default', array('controller'=>'providers', 'action'=>'edit', 'id'=>$provider->id));?>" class="btn btn-default btn-xs" role="button" title="Редактировать">
                  <span class="glyphicon glyphicon-edit" aria-hidden="true"></span> 
                </a>
                <button title="Удалить" role="button" class="js-ajax-remove btn btn-default btn-xs" 
                        postparamname="providerid" 
                        providerid="<?=$provider->id;?>" 
                        url="<?=$this->url('admin/default', ['controller'=>'providers', 'action'=>'remove']);?>" 
                        confirm='Удалить товар "<?=$provider->name;?>"?' 
                        removeselector=".table-row-provider-id-<?=$provider->id;?>">
                    <span aria-hidden="true" class="glyphicon glyphicon-remove"></span>
                </button>
            </td>
        </tr>
    <? endforeach; ?>
    </tbody>
</table>
<? endif; ?>

<button title="Удалить отмеченные" class="js-ajax-bulk-remove btn btn-default btn-md" role="button"
        checkboxselector=".js-provider-checkbox" 
        postparamname="providerid" 
        url="<?=$this->url('admin/default', ['controller'=>'providers', 'action'=>'remove']);?>" 
        confirm='Удалить отмеченные товары?' 
        removeselector=".table-row-provider-id-">
  <span class="glyphicon glyphicon-remove" aria-hidden="true"></span> 
</button>