<?php 
$title = 'Добавление товара';
$this->headtitle($title);
?>

<h3><?= $this->escapehtml($title); ?></h3>

<?php
$form->prepare();
echo $this->form()->openTag($form);
?>
<h4>Информация о товаре</h4>
<?php $elem = $form->get('type_prefix');?>
<div class="form-group">
    <label class='col-xs-2 control-label'><?=$elem->getOption('label'); ?></label>
    <div class='col-xs-4'>
        <? echo $this->formElement($elem); echo $this->formElementErrors($elem); ?>
    </div>
</div>
<?php $elem = $form->get('model');?>
<div class="form-group">
    <label class='col-xs-2 control-label'><?=$elem->getOption('label'); ?></label>
    <div class='col-xs-4'>
        <? echo $this->formElement($elem); echo $this->formElementErrors($elem); ?>
    </div>
</div>
<?php $elem = $form->get('short_descr');?>
<div class="form-group">
    <label class='col-xs-2 control-label'><?=$elem->getOption('label'); ?></label>
    <div class='col-xs-4'>
        <? echo $this->formElement($elem); echo $this->formElementErrors($elem); ?>
    </div>
</div>
<?php $elem = $form->get('descr');?>
<div class="form-group">
    <label class='col-xs-2 control-label'><?=$elem->getOption('label'); ?></label>
    <div class='col-xs-4'>
        <? echo $this->formElement($elem); echo $this->formElementErrors($elem); ?>
    </div>
</div>

<h4>Изображения и видео</h4>
<?php echo $this->formElement($form->get('image')) ?>
<div class="form-group">
    <? $elem = $form->get('imagefile'); ?>
    <label class='col-xs-2 control-label'><?=$elem->getOption('label'); ?></label>
    <div class='col-xs-4'>
        <?php
        echo $this->formElement($elem);
        echo $this->formElementErrors($elem); ?>
    </div>
</div>

<?php echo $this->formElement($form->get('small_image')) ?>
<div class="form-group">
    <? $elem = $form->get('smallimagefile'); ?>
    <label class='col-xs-2 control-label'><?=$elem->getOption('label'); ?></label>
    <div class='col-xs-4'>
        <?php
        echo $this->formElement($elem);
        echo $this->formElementErrors($elem); ?>
        <div class="checkbox"><label><? echo $this->formElement($form->get('makesmallimagefromimage')) ?>
        <? echo $form->get('makesmallimagefromimage')->getAttribute('placeholder'); ?></label></div>
    </div>
</div>


<?php $elem = $form->get('video');?>
<div class="form-group">
    <label class='col-xs-2 control-label'><?=$elem->getOption('label'); ?></label>
    <div class='col-xs-4'>
        <? echo $this->formElement($elem); echo $this->formElementErrors($elem); ?>
    </div>
</div>


<h4>SEO</h4>
<?php $elem = $form->get('meta_title');?>
<div class="form-group">
    <label class='col-xs-2 control-label'><?=$elem->getOption('label'); ?></label>
    <div class='col-xs-4'>
        <? echo $this->formElement($elem); echo $this->formElementErrors($elem); ?>
    </div>
</div>
<?php $elem = $form->get('meta_descr');?>
<div class="form-group">
    <label class='col-xs-2 control-label'><?=$elem->getOption('label'); ?></label>
    <div class='col-xs-4'>
        <? echo $this->formElement($elem); echo $this->formElementErrors($elem); ?>
    </div>
</div>


<div class="form-group">
    <?php echo $this->formElement($form->get('addItem')) ?>
</div>
<?php echo $this->form()->closeTag() ?>

