<?php 
$title = 'Смена пароля';
$this->headtitle($title);
?>
<div class="tabs-block">
    <?php echo $this->navigation('Navigation')->menu()
            ->setContainer($this->navigation('Navigation')->findOneBy('id','home-lk'))
            ->setMaxDepth(0)
            ->setPartial(array('partial/lkMenu.phtml', 'Account'))
            ;
    ?>
</div>

<div><?=$title;?></div>

<div class="form-type1">
<?php
$form->prepare();
echo $this->form()->openTag($form);
echo $this->formCollection($form);
echo $this->form()->closeTag($form); 
?>
</div>