<? 
$title = 'Информационные страницы. Разделы.';
$this->headtitle('Администрирование. '.$title);
?>
<div class="page-header">
  <h1><?=$title;?></h1>
</div>

<a href="<?=$this->url('admin/default', array('controller'=>'content', 'action'=>'addsection', 'id' => ($sectionId > 0 ? $sectionId : '')));?>" class="btn btn-primary btn-lg mrg-b-lg">
  Добавить раздел
</a>
<? if ($sectionId > 0) { ?>
<a href="<?=$this->url('admin/default', array('controller'=>'content', 'action'=>'texts', 'id' => $sectionId));?>" class="btn btn-primary btn-lg mrg-b-lg">
  Статьи
</a>
<? } ?>
<? if (isset($sections) && count($sections)) { ?>
<table class="table table-striped table-sortable">
    <thead>
        <tr>
            <th></th>
            <th></th>
            <th>ID</th>
            <th>Название</th>
            <th>Ссылка</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        <?  foreach ($sections as $section) { ?>
        <tr id="<?=$section->id;?>" class="table-row-section-id-<?=$section->id;?>">
            <td><span class="glyphicon glyphicon-resize-vertical"></span></td>
            <td><input type="checkbox" name="ids[]" value="<?=$section->id;?>" class="js-section-checkbox"/></td>
            <td><?=$section->id;?></td>
            <td><?=$section->name;?></td>
            <td>/pages/<?=$section->alias;?></td>
            <td>
                <a href="<?=$this->url('admin/default', array('controller'=>'content', 'action'=>'index', 'id'=>$section->id));?>" class="btn btn-default btn-xs" role="button" title="Разделы">
                  <span class="glyphicon glyphicon-folder-close" aria-hidden="true"></span> 
                </a>
                <a href="<?=$this->url('admin/default', array('controller'=>'content', 'action'=>'texts', 'id'=>$section->id));?>" class="btn btn-default btn-xs" role="button" title="Тексты">
                  <span class="glyphicon glyphicon-file" aria-hidden="true"></span> 
                </a>
                <a href="<?=$this->url('home/content/section', array('alias'=>$section->alias));?>" target="_blank" class="btn btn-default btn-xs" role="button" title="На сайте">
                  <span class="glyphicon glyphicon-th" aria-hidden="true"></span> 
                </a>
                <a href="<?=$this->url('admin/default', array('controller'=>'content', 'action'=>'editsection', 'id'=>$section->id));?>" class="btn btn-default btn-xs" role="button" title="Редактировать">
                  <span class="glyphicon glyphicon-edit" aria-hidden="true"></span> 
                </a>
                <button title="Удалить" role="button" class="js-ajax-remove btn btn-default btn-xs" 
                        postparamname="sectionid" 
                        sectionid="<?=$section->id;?>" 
                        url="<?=$this->url('admin/default', ['controller'=>'content', 'action'=>'removeSection']);?>" 
                        confirm='Удалить раздел "<?=$section->name;?>"?' 
                        removeselector=".table-row-section-id-<?=$section->id;?>">
                  <span aria-hidden="true" class="glyphicon glyphicon-remove"></span> 
                </button>
            </td>
        </tr>
        <? } ?>
    </tbody>
</table>

<button title="Сохранить порядок" class="js-ajax-save-sort btn btn-default btn-md" role="button"
        url="<?=$this->url('admin/default', ['controller'=>'content', 'action'=>'savesort', 'sub' => 'sections']);?>" 
        parentid="<?=$sectionId;?>"
        >
  <span class="glyphicon glyphicon-floppy-disk" aria-hidden="true"></span> 
  <span class="glyphicon glyphicon-sort" aria-hidden="true"></span> 
</button>

<button title="Удалить отмеченные" class="js-ajax-bulk-remove btn btn-default btn-md" role="button"
        checkboxselector=".js-section-checkbox" 
        postparamname="sectionid" 
        url="<?=$this->url('admin/default', ['controller'=>'content', 'action'=>'removeSection']);?>" 
        confirm='Удалить отмеченные разделы?' 
        removeselector=".table-row-section-id-">
  <span class="glyphicon glyphicon-remove" aria-hidden="true"></span> 
</button>

<?php if ($sections instanceof Zend\Paginator\Paginator)  
        echo $this->paginationControl($sections, 'sliding', array('partial/paginatorAdmin.phtml', 'admin'),
            array(
                'route' => 'admin/default', 
                'params' => ['controller' => 'content', 'action' => 'index', 'sub' => $sub],
                'options' => ['query' => $query],
            ));
    ?>

<? } ?>