<div class="page-header">
    <h1>Сводка</h1>
</div>
<!--div class="row">
    <div class="col-md-4">
        <ul class="nav nav-pills">
            <li role="presentation"><a href="#">Заказов за сегодня <span class="badge">42</span></a></li>
        </ul>
        <div class="panel panel-default">
            <div class="panel-heading">Последние заказы</div>
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>Номер</th>
                        <th>От кого</th>
                        <th>Дата</th>
                        <th>Сумма</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>156334</td>
                        <td>Labs</td>
                        <td>23.08.2015 12:17</td>
                        <td>12345.23</td>
                    </tr>
                    <tr>
                        <td>15334</td>
                        <td>Labs</td>
                        <td>23.08.2015 12:17</td>
                        <td>12345.23</td>
                    </tr>
                    <tr>
                        <td>156334</td>
                        <td>Labs</td>
                        <td>23.08.2015 12:17</td>
                        <td>12345.23</td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
    <div class="col-md-4">
        ченить еще
    </div>
    <div class="col-md-4">
        ченить еще
    </div>
</div-->

<? //var_dump($this->layout()->admin);?>