<? $IMG = $this->layout()->settings['images']; ?>
<div class="middle_inner">
    <section class="content_wrap fullwidth cmsms_woo">
        <!--_________________________ Start Content _________________________ -->
        <div class="middle_content entry" role="main">
            <div itemscope itemtype="http://schema.org/Product" id="product-1955" class="cmsms_single_product post-1955 product type-product status-publish has-post-thumbnail featured shipping-taxable purchasable product-type-simple instock">
                <div class="cmsms_product_left_column">
                    <div class="images cmsms_product_images">
                        <? $images = $model->getImages(); $firstImage = array_shift($images); ?>
                        <? if ($firstImage != null) { ?>
                        <a href="<?=implode('', [$IMG['host'],$IMG['tyres'],$IMG['models'],$firstImage])?>" itemprop="image" class="woocommerce-main-image cmsms_product_image" title="" rel="ilightbox[cmsms_product_gallery]">
                            <img width="500" height="500" 
                                 src="<?=implode('', [$IMG['host'],$IMG['tyres'],$IMG['models'],$firstImage])?>" 
                                 class="attachment-shop_single size-shop_single wp-post-image" 
                                 alt="<?=$firstImage;?>" title="" 
                                 sizes="(max-width: 500px) 100vw, 500px" />
                        </a>
                        <? } else { ?>
                        <img width="100%" src="holder.js/290x290/#aaa:#fff/text:Нет фото" />
                        <? } ?>
                        <? if (count($images) > 0) { ?>
                        <div class="thumbnails cmsms_product_thumbs">
                            <? foreach ($images as $image) { ?>
                            <a href="<?=implode('', [$IMG['host'],$IMG['tyres'],$IMG['models'],$image])?>" class="cmsms_product_thumb" title="" rel="ilightbox[cmsms_product_gallery]">
                                <img width="90" height="90" src="<?=implode('', [$IMG['host'],$IMG['tyres'],$IMG['models'],$image])?>" class="attachment-shop_thumbnail size-shop_thumbnail" alt="<?=$image;?>" sizes="(max-width: 90px) 100vw, 90px" />
                            </a>
                            <? } ?>
                        </div>
                        <? } ?>
                    </div>
                </div>
                <div class="summary entry-summary cmsms_product_right_column">
                    <h1 itemprop="name" class="product_title entry-title"><?= $brand->name ?> <?= $model->name ?></h1>
                    
                    <div itemprop="description">
                        <p>Lorem ipsum dolor sit amet, velit possit impetus ea quo, at tractatos incorrupte his. Sed nisl viderer ad, mel delicata iudicabit an, rebum tollit causae per eu. Luptatum conclusionemque ius at, vix no sint iisque urbanitas. Voluptaria disputando an has, idque nemore iuvaret eu usu.</p>
                    </div>
                    
                    <div itemprop="offers" itemscope itemtype="http://schema.org/Offer">
                        <? if (isset($tyres) && count($tyres) > 0) { ?>
                            <table class="cmsms_table">
                                <thead>
                                    <tr class="cmsms_table_row_header">
                                        <th class="cmsms_table_cell_alignleft">Размер</th>
                                        <th class="cmsms_table_cell_alignleft">Индексы</th>
                                        <? if ($model->season == 'winter') { ?>
                                        <th class="cmsms_table_cell_alignleft">Шипы</th>
                                        <? } ?>
                                        <th class="cmsms_table_cell_alignleft">Опции</th>
                                        <th class="cmsms_table_cell_alignleft">Кол-во</th>
                                        <th class="cmsms_table_cell_alignleft">Цена</th>
                                        <th class="cmsms_table_cell_alignleft">Поставщик</th>
                                        <th></th>
                                    </tr>
                                </thead>
                            <? foreach ($tyres as $tyre) { ?>
                                <tbody>
                                    <? foreach ($tyre->getPrices() as $price) { ?>
                                    <tr>
                                        <td class="cmsms_table_cell_alignleft">
                                            <a href="<?=$this->url('home/tyres/tyre', ['brandName'=>$brand->name, 'modelName'=>$model->name, 'width' => $tyre->width, 'height' => $tyre->height, 'diameter'=>$tyre->diameter]);?>">
                                                <?=sprintf("%s/%s R%s", $tyre->width, $tyre->height, $tyre->diameter)?>
                                            </a>
                                        </td>
                                        <td class="cmsms_table_cell_alignleft"><?=sprintf("%s %s", $tyre->load, $tyre->speed)?></td>
                                        <? if ($model->season == 'winter') { ?>
                                        <td class="cmsms_table_cell_alignleft">
                                            <?=$tyre->spikes == 1 ? 'Есть':'Нет';?>
                                        </td>
                                        <? } ?>
                                        <td class="cmsms_table_cell_alignleft">
                                            <?
                                            $options = [];
                                            if ($tyre->RFT == 1)
                                                $options[] = 'Run Flat';
                                            if ($tyre->XL == 1)
                                                $options[] = 'Extra Load';
                                            echo implode(', ', $options);
                                            ?>
                                        </td>
                                        <td class="cmsms_table_cell_alignleft"><?=$price->quantity?></td>
                                        <td class="cmsms_table_cell_alignleft">
                                            <p class="price"><span class="amount"><?=$price->price?> RUB</span></p>
                                            <meta itemprop="price" content="<?=$price->price?>" />
                                            <meta itemprop="priceCurrency" content="RUB" />
                                            <link itemprop="availability" href="http://schema.org/InStock" />
                                        </td>
                                        <td class="cmsms_table_cell_alignleft"><?=$price->getProvider()->name;?></td>
                                        <td>
                                            <button count="1" objecttype="tyres" objectid="<?=$price->id;?>" class="btn btn-default js-ajax-addtocart">В корзину</button>
                                            
                                            <!--form class="cart" method="post">
                                                <div class="quantity"><input type="number" step="1" min="1"  name="quantity" value="1" title="Qty" class="input-text qty text" size="4" /></div>
                                                <input type="hidden" name="add-to-cart" value="<?=$price->id;?>" />
                                                <button type="submit" class="single_add_to_cart_button button alt">Add to cart</button>
                                            </form-->
                                        </td>
                                    </tr>
                                    <? } ?>
                                </tbody>
                            <? } ?>
                            </table>
                        <? } elseif (isset($isFoundTyres) && $isFoundTyres == false) { ?>
                            В продаже нет шин данной модели
                        <? } ?>
                    </div>
                    
                    <div class="product_meta">
                    </div>
                </div>
                <div class="cl"></div>
<?/*
                <div class="cmsms_tabs tabs_mode_tab cmsms_woo_tabs">
                    <ul class="cmsms_tabs_list">
                        <li class="description_tab cmsms_tabs_list_item">
                            <a href="../../index.html%3Fp=1955.html#tab-description">
                                <span>Description</span>
                            </a>
                        </li>
                        <li class="additional_information_tab cmsms_tabs_list_item">
                            <a href="../../index.html%3Fp=1955.html#tab-additional_information">
                                <span>Additional Information</span>
                            </a>
                        </li>
                        <li class="reviews_tab cmsms_tabs_list_item">
                            <a href="../../index.html%3Fp=1955.html#tab-reviews">
                                <span>Reviews (0)</span>
                            </a>
                        </li>
                    </ul>
                    <div class="cmsms_tabs_wrap">
                        <div class="entry-content cmsms_tab" id="tab-description">
                            <div class="cmsms_tab_inner">
                                <h2>Product Description</h2>
                                <style type="text/css"></style><p>Lorem ipsum dolor sit amet, velit possit impetus ea quo, at tractatos incorrupte his. Sed nisl viderer ad, mel delicata iudicabit an, rebum tollit causae per eu. Luptatum conclusionemque ius at, vix no sint iisque urbanitas. Voluptaria disputando an has, idque nemore iuvaret eu usu. Mea fuisset democritum in.</p>
                            </div>
                        </div>
                        <div class="entry-content cmsms_tab" id="tab-additional_information">
                            <div class="cmsms_tab_inner">
                                <h2>Additional Information</h2>
                                <table class="shop_attributes">
                                    <tr class="">
                                        <th>Manufacturer</th>
                                        <td><p>GMC</p>
                                        </td>
                                    </tr>
                                    <tr class="alt">
                                        <th>Vehicle Types</th>
                                        <td><p>All</p>
                                        </td>
                                    </tr>
                                    <tr class="">
                                        <th>Warranty</th>
                                        <td><p>full warranty</p>
                                        </td>
                                    </tr>
                                    <tr class="alt">
                                        <th>Installation</th>
                                        <td><p>professional only</p>
                                        </td>
                                    </tr>
                                </table>
                            </div>
                        </div>
                        <div class="entry-content cmsms_tab" id="tab-reviews">
                            <div class="cmsms_tab_inner">
                                <div id="reviews">
                                    <div id="comments">
                                        <div class="cmsms_star_rating" itemprop="aggregateRating" itemscope itemtype="http://schema.org/AggregateRating" title="Rated 0 out of 5">
                                            <div class="cmsms_star_trans_wrap">
                                                <span class="cmsms_theme_icon_star_full cmsms_star"></span>
                                                <span class="cmsms_theme_icon_star_full cmsms_star"></span>
                                                <span class="cmsms_theme_icon_star_full cmsms_star"></span>
                                                <span class="cmsms_theme_icon_star_full cmsms_star"></span>
                                                <span class="cmsms_theme_icon_star_full cmsms_star"></span>
                                            </div>
                                            <div class="cmsms_star_color_wrap" style="width:0%">
                                                <div class="cmsms_star_color_inner">
                                                    <span class="cmsms_theme_icon_star_full cmsms_star"></span>
                                                    <span class="cmsms_theme_icon_star_full cmsms_star"></span>
                                                    <span class="cmsms_theme_icon_star_full cmsms_star"></span>
                                                    <span class="cmsms_theme_icon_star_full cmsms_star"></span>
                                                    <span class="cmsms_theme_icon_star_full cmsms_star"></span>
                                                </div>
                                            </div>
                                            <span class="rating dn"><strong itemprop="ratingValue">0</strong> out of 5</span>
                                        </div>
                                        <h2>Reviews</h2>
                                        <p class="woocommerce-noreviews">There are no reviews yet.</p>
                                    </div>

                                    <div id="review_form_wrapper">
                                        <div id="review_form">
                                            <div id="respond" class="comment-respond">
                                                <h3 id="reply-title" class="comment-reply-title">Be the first to review &ldquo;JS-20 Tire Chains&rdquo; <small><a rel="nofollow" id="cancel-comment-reply-link" href="../../index.html%3Fp=1955.html#respond" style="display:none;">Cancel reply</a></small></h3>				<form action="http://garage.cmsmasters.net/wp-comments-post.php" method="post" id="commentform" class="comment-form" novalidate>
                                                    <p class="comment-form-rating"><label for="rating">Your Rating</label><select name="rating" id="rating">
                                                            <option value="">Rate&hellip;</option>
                                                            <option value="5">Perfect</option>
                                                            <option value="4">Good</option>
                                                            <option value="3">Average</option>
                                                            <option value="2">Not that bad</option>
                                                            <option value="1">Very Poor</option>
                                                        </select></p><p class="comment-form-comment"><label for="comment">Your Review</label><textarea id="comment" name="comment" cols="45" rows="8" aria-required="true"></textarea></p><p class="comment-form-author"><label for="author">Name <span class="required">*</span></label> <input id="author" name="author" type="text" value="" size="30" aria-required="true" /></p>
                                                    <p class="comment-form-email"><label for="email">Email <span class="required">*</span></label> <input id="email" name="email" type="text" value="" size="30" aria-required="true" /></p>
                                                    <p class="form-submit"><input name="submit" type="submit" id="submit" class="submit" value="Submit" /> <input type='hidden' name='comment_post_ID' value='1955' id='comment_post_ID' />
                                                        <input type='hidden' name='comment_parent' id='comment_parent' value='0' />
                                                    </p><p style="display: none;"><input type="hidden" id="akismet_comment_nonce" name="akismet_comment_nonce" value="1623e93a8c" /></p><p style="display: none;"><input type="hidden" id="ak_js" name="ak_js" value="27"/></p>				</form>
                                            </div><!-- #respond -->
                                        </div>
                                    </div>

                                    <div class="clear"></div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
*/?>

                <meta itemprop="url" content="http://garage.cmsmasters.net/product/js-20-tire-chains/" />

            </div><!-- #product-1955 -->


        </div>
        <!-- _________________________ Finish Content _________________________ -->

    </section>
</div>